export enum Symbol {
  XBTUSD = 'XBTUSD',
  ETHUSD = 'ETHUSD',
  ADAXXX = 'ADAM19',
  BCHXXX = 'BCHH19',
  EOSXXX = 'EOSH19',
  ETHXXX = 'ETHH19',
  LTCXXX = 'LTCH19',
  TRXXXX = 'TRXH19',
  XRPXXX = 'XRPH19'
}
