export enum Symbol {
  XBTUSD = 'XBTUSD',
  ETHUSD = 'ETHUSD',
  ADAXXX = 'ADAM19',
  BCHXXX = 'BCHM19',
  EOSXXX = 'EOSM19',
  ETHXXX = 'ETHM19',
  LTCXXX = 'LTCM19',
  TRXXXX = 'TRXM19',
  XRPXXX = 'XRPM19'
}
